// import toast from "react-hot-toast";
import { useLoaderData } from "react-router-dom";
import MyParcelCard from "./MyParcelCard";


const MyParcel = () => {
    const myParcelData = useLoaderData();

    
    return (
        <div className="w-full p-14">
            <table className="table">
                {/* head */}
                <thead>
                    <tr className="bg-green-300  font-bold mt-12 rounded-md text-sm text-black  grid grid-cols-10">
                        <td>Parcel Type</td>
                        <td>Req. Del. Date</td>
                        <td>Apt Del Date</td>                    
                        <td>Booking Date</td> {/*(Auto Generated by new Date()) */}             
                        <td>Del. Men ID</td>
                        <td>Status</td>
                        <td>update</td>
                        <td>cancel</td>
                        <td>review</td>
                        <td>pay</td>
                    </tr>
                </thead>
                <tbody className="">

                    {
                        myParcelData?.map((parcelContent, index) => <MyParcelCard  parcelContent={parcelContent} index={index} key={index}></MyParcelCard>)
                    }

                </tbody>

            </table>
        </div>
    );
};

export default MyParcel;